buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("io.spring.javaformat:spring-javaformat-gradle-plugin:0.0.39")
    }
}

plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.16'
    id 'io.spring.dependency-management' version '1.1.7'
}

apply plugin: 'io.spring.javaformat'
apply plugin: 'checkstyle'

group = 'com.izeye.apps'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    checkstyle("io.spring.javaformat:spring-javaformat-checkstyle:0.0.39")
}

springBoot {
    mainClass = 'com.izeye.app.wordgame.web.WordGameWebApplication'
}

test {
    useJUnitPlatform()
}

wrapper {
    gradleVersion = '8.12'
}
